version: '3.8'

services:
  telegram-bot:
    image: ghcr.io/idoavrah/mlbgamebot:latest
    user: root
    env_file:
      - .env
    volumes:
      - data:/app/data
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      restart_policy:
        condition: always
        delay: 30s

volumes:
  data:
