version: '3.8'

services:
  telegram-bot:
    image: bot
    restart: always
    env_file:
      - .env
    volumes:
      - data:/app/data
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  data:
